version: '3.8'

services:
  fastapi:
    build:
      context: fastapi/
      dockerfile: Dockerfile
    image: fastapi-app
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi
    volumes:
      - mis_datos:/data
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  streamlit:
    build:
      context: streamlit/
      dockerfile: Dockerfile
    image: streamlit-app
    depends_on:
      - fastapi
    ports:
      - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit
    volumes:
      - mis_datos:/data

networks:
  deploy_network:
    driver: bridge

volumes:
  mis_datos: {}
